version: "3.8"

services:
  app:
    build: .
    env_file:
      - ./.env.local.example
    container_name: app
    volumes:
      - .:/usr/src:rw
    ports:
      - 3000:3000
    command: npm run dev
    restart: always
